# Generated by Django 3.0.5 on 2020-05-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
